### ISSUE TITLE
Item based options

### ISSUE THREAD

**Issue by ShawnVK** [geheur/More-menu-entry-swaps#1]
Can you also add item based menu entry swapper on hover?

In the bank, you can use these hotkeys to change the menu entries, but what if when u hover over a certain item, it automatically changes the menu entry?

For example: When you hover over stamina dose 1 in your bank, it automatically changes to Withdraw-1. I think it would be cool, idk how possible it is but I'd like to suggest it :)

This is already doable with the current settings on your plugin but doing menu entry swap on hover rather than hotkey press would be one step better imo.

**Comment by geheur** [comment]
Not sure RuneLite would accept this automatic intelligent left-click swap, I'd have to ask.

Sorry for late response, it appears that I accidentally disabled email notifications on this repo :(.

**Comment by geheur** [comment]
Runelite definitely won't allow this.
