### ISSUE TITLE
Possible feature request

### ISSUE THREAD

**Issue by Prysm01** [geheur/More-menu-entry-swaps#10]
Hey there, I'm very sorry if this is the wrong place to write this, I am very new to runelite plugins.. Anyways I was looking for a plug in the seemed to be very close to this one, I'm smelting and was hoping for a keybind I could setup to withdraw a set amount of ore... for example, I hold F and left click on iron ore in my bank and that would make 9 (or whatever X is set to) iron ore be sent to my inventory. 

It seemed like your plugin is very close to making this happen... or maybe it is able to and I'm clearly using it incorrectly... haha... 

Well either way thanks for the plugin and keep up the great work!

**Comment by geheur** [comment]
are you asking for item-specific swaps like this? https://github.com/geheur/More-menu-entry-swaps/issues/1
