### ISSUE TITLE
"pick-lock,trapdoor" swaps HAM Trapdoor to Examine instead of Pick-Lock

### ISSUE THREAD

**Issue by fuzxi** [geheur/More-menu-entry-swaps#15]
![2022-08-05-02-46-41](https://user-images.githubusercontent.com/33790641/183052312-ab40ff64-d261-4d40-a1a5-44f1d00de974.png)
This is the HAM hideout trapdoor west of Lumbridge. I copy-pasted the swap text directly from the instructions section. Expected behavior is for Pick-Lock to appear above all options as the left-click option. It only works as expected if I also hide the examine option.

**Comment by fuzxi** [comment]
Actually, it still doesn't work quite as expected. With the examine option hidden, the trapdoor is left-click Pick-Lock, but if there's anything in front of it that has an examine option (e.g. dead tree or spider), whatever's in front of it will have its left-click option swapped to examine.

**Comment by geheur** [comment]
Should no longer happen.
