### ISSUE TITLE
Suggestion: Add custom hotkeys to the custom swaps

### ISSUE THREAD

**Issue by cow1337killer3** [geheur/More-menu-entry-swaps#16]
It'd be awesome if we could specify a field at the beginning or ending of a custom swap line, which specifies a modifier key that needs to be currently pressed for the swap to happen.

An example is the Construction cape. I want to left click "Wear", [shift + left click] for "Tele to POH", and [alt + left click] for "Teleport". 

This would look like:
```
Wear,Construct. cape (t)
shift,Tele to POH,Construct. cape (t)
alt,Teleport,Construct. cape (t)
```

Or have the modifier key at the end if that makes it easier to parse.

**Comment by geheur** [comment]
This is now a feature.
