### ISSUE TITLE
POH Swaps not working anymore

### ISSUE THREAD

**Issue by robuuuste** [geheur/More-menu-entry-swaps#18]
Hi, I noticed several (if not all) POH swaps such as jewellery box, fairy ring/tree, occult altar, nexus etc. are not working anymore since the last RuneLite update.

**Comment by derekmu** [comment]
Same for me, I have 1 bound to Last-destination and Shift bound to Tree for the Spirit tree/Fairy ring and neither works.

**Comment by SilleeCookie** [comment]
I am still having issues with the option for the tree on my spirit ring combo, everything else works, any fixes for this yet?

**Comment by geheur** [comment]
Should be fixed.

I don't know anything about the "Tree" option issue. All I know is it is rare. If you can find a way to make it happen let me know.
