### ISSUE TITLE
[Bug] Clicking too fast disables my left and right clicks

### ISSUE THREAD

**Issue by claytray** [geheur/More-menu-entry-swaps#20]
High alching for example in the same spot then spam clicking disables my mouse. I know it's this plugin because I turned it off and spam clicked a few times and no isues.

**Comment by geheur** [comment]
what swaps do you use? You dont' have cancel hidden, right?

**Comment by claytray** [comment]
My custom swaps are

"Attack,General Graardor
*attack,Sergeant Strongstack*
collect,torfinn
*Rellekka,travel*"

My Custom hides are

"Cancel
examine, banker
examine, vorkath
examine, toxic blowpipe
Rellekka,torfinn
Rub,amulet of glory
Use,amulet of glory"

**Comment by geheur** [comment]
yeah don't hide cancel. When you have a spell selected, despite what's shown in the top left of the screen, the only option is actually "Cancel", so if you hide it there are no menu entries so of course your clicks do not do anything.

**Comment by geheur** [comment]
I should probably add something to prevent removing cancel when it's the only menu entry. but for now that's how it works. don't hide "Cancel".

**Comment by claytray** [comment]
Ahhh, understood!
Thank you.

Also, is it possible to add a command to hide every Examine option

example: Examine, *

**Comment by geheur** [comment]
`examine,*` works for me.
