### ISSUE TITLE
Don't prioritize pray/spec lower than a swap

### ISSUE THREAD

**Issue by vikke1234** [geheur/More-menu-entry-swaps#24]
Could these be added to the default config with some comment to keep them the lowest in order to not make pray/spec lower priority than a swap (likely not what was intended in the first place). 

```
// Keep these the lowest, if anything is below, you will be able to click through
// these on the object.
use, special attack
activate, quick-prayers
deactivate, quick-prayers
```

**Comment by geheur** [comment]
8662db8 for release in 2.1.0
