### ISSUE TITLE
Examine/Cancel late removal works for Cancel but not Examine

### ISSUE THREAD

**Issue by iatethedinosaurs** [geheur/More-menu-entry-swaps#25]
Hello,

I sideloaded the lastest version of your plugin into Runelite to try out the new late removal and noticed that while it does work for Cancel (`*, cancel` the menu entry swapper shift+left-click config option still properly show) it doesn't seem to work for Examine (`*, examine` the shift+left-click config options stop appearing).

I tested this making sure that only the base Runelite plugins were loaded, to ensure that it wasn't another plugin from the Hub causing issues. I checked the debug log to see if any errors were being generated, but there didn't appear to be. If there is any more information I can provide, please let me know.

**Comment by geheur** [comment]
World for me testing on clay rock at the crafting guild.
btw it's `cancel` and `examine,*`. Maybe that is the issue?

**Comment by geheur** [comment]
Also, the `cancel` removal has nothing to do with shift-right-click config option. That one is for cancelling targetted spell casts by clicking anywhere in the game that isn't a valid target..

**Comment by iatethedinosaurs** [comment]
Sorry, I do have it as `examine, *` and `cancel, *`. Thank you for clarifying what the cancel removal.
Okay, so I tested it at the Crafting Guild clay rock and it does seem to show the shift-right click config options for objects (like the clay rock). 

Would you be able to confirm if it works for inventory items? That's where I was seeing that they aren't being added. I should have specified that.
 
My apologies. I opened the issue late night, so I was a bit tired and missed some details.

**Comment by geheur** [comment]
Ah I see that now. Thanks for reporting this.

**Comment by geheur** [comment]
Fixed 9741fa25fe980081e71b5e096450bdff90f18210

**Comment by iatethedinosaurs** [comment]
Recompiled and can confirm that it's working now. Thank you!
