### ISSUE TITLE
Collapse all menus by default.

### ISSUE THREAD

**Issue by Toasty64** [geheur/More-menu-entry-swaps#26]
Would it be possible to collapse all menus when loading plugin settings? Currently the plugin starts with all boxes open and if many swaps are in use it is annoying having to scroll to find what you need.

Example of what I am looking for: 
![image](https://github.com/geheur/More-menu-entry-swaps/assets/22701517/0442c658-14db-415c-a4c6-d99a5ceeed01)

**Comment by geheur** [comment]
Problem is that this setting is not changeable per-person.
Ideally it would just remember the old state you last had it in. Maybe runelite would accept such a change. But from my end in this plugin it's either all or nothing, and I'd rather have them all expanded than all closed.

**Comment by geheur** [comment]
This is now the default.
