### ISSUE TITLE
[Request] Disable "cancel, *" on Slayer master UI

### ISSUE THREAD

**Issue by iatethedinosaurs** [geheur/More-menu-entry-swaps#27]
Would it be possible to add an exception to `cancel, *` to prevent it from hiding the option to "Cancel Task" on the Slayer menu?

**Comment by geheur** [comment]
what if you just hid `cancel` instead of `cancel,*`?

**Comment by iatethedinosaurs** [comment]
Looks like hiding just `cancel` still has the same effect and hides the Cancel Task in the Slayer menu.

**Comment by geheur** [comment]
is this with late removal on?

**Comment by geheur** [comment]
I'm not sure what the correct solution would be, at least in this plugin. I would use the "no examine" plugin, I bet that one only removes true cancel options and not just any option named cancel.
I'm not adding a checkbox specifically for cancelling slayer tasks. And I don't know if it's worth making a way for people to hide menu entries by their `Type`.

**Comment by iatethedinosaurs** [comment]
No worries. It's not that big of a deal. I just thought it would be something to bring up. Thank you!
