### ISSUE TITLE
Blackjacking: Cannot set Lure or Knock-out

### ISSUE THREAD

**Issue by EnuDelrum** [geheur/More-menu-entry-swaps#29]
For some reason, you cannot set the custom swap or custom shift to be **Lure** or **Knock-out** for the [Bandit (Pollnivneach)](https://oldschool.runescape.wiki/w/Bandit_(Pollnivneach)) or the [Menaphite Thug](https://oldschool.runescape.wiki/w/Menaphite_Thug). Fixing this would help with [blackjacking](https://oldschool.runescape.wiki/w/Thieving_training#Levels_45%E2%80%9349,_65%E2%80%9391/99:_Blackjacking). You can set other actions though, such as **Pickpocket**.

**Comment by geheur** [comment]
it is that way because jagex said not to swap those menu entries. https://github.com/geheur/More-menu-entry-swaps/wiki/Custom-swaps#custom-swap-limitations
