### ISSUE TITLE
Portal Nexus swap

### ISSUE THREAD

**Issue by thebinaryeagle** [geheur/More-menu-entry-swaps#3]
Would be very handy to have a keybind that switches the left-click option of the portal nexus to 'Teleport menu' when held rather than whatever destination you have set. Clicking the ground near the nexus and then right-clicking it while moving is a bit tedious for farm runs and the like.

**Comment by geheur** [comment]
https://github.com/runelite/runelite/pull/13563

**Comment by Ririshi** [comment]
The fact that this isn't supported by runelite itself shouldn't mean it shouldn't be supported here, imo. The spirit tree / fairy ring also has a runelite base menu entry swapper option, but this plugin still supports a custom hotkey option for it. On that note, I would like to +1 support for the portal nexus and also request support for the ornate jewelry box, similar to how the spirit tree/ fairy ring hotkeys can be set (but with "teleport menu" and "last destination" options instead).

**Comment by geheur** [comment]
Would be useful. The keybind should swap the second option with the first option, regardless of what the first menu option is. This would make this option useful regardless of what left-click option is set in Menu Entry Swapper.

**Comment by geheur** [comment]
Finally added this, sorry for the wait. https://github.com/runelite/plugin-hub/pull/2309
