### ISSUE TITLE
Arclight left-click options don't work

### ISSUE THREAD

**Issue by KosmicAnosmic** [geheur/More-menu-entry-swaps#31]
Put simply, I cannot change the left-click options for my Arclight. By default, left click drops my Arclight. It doesn't matter if I use CMS to reset or swap the default left-click option, nothing changes. It DOES work for shift+left click, but that's all.

This persists even if I disable CMS, so I recognize it's entirely possible there's some other plugin causing this issue. I just figured this would be the best place to try and sort this out. 

Thanks in advance!

**Comment by geheur** [comment]
if it still happens when the plugin is disabled then it's not this plugin.
The only other plugin I can think of which allows drop swap on arclight is "left click dropper", maybe you have that? I wasn't aware that one overrides CMS though.
