### ISSUE TITLE
Change the bank eat/wield/etc. option to configure for rune pouch

### ISSUE THREAD

**Issue by ImFlizz** [geheur/More-menu-entry-swaps#32]
The option under the bank section 'eat/wield/etc' allows you to set a hot key to eat food, wear equipment and other misc actions on items. For rune pouch this is currently empty. Jagex added the "configure" option today. It should be switched

**Comment by geheur** [comment]
What if you shift-right-click and change the rune pouch in the inventory to deposit-1? Using runelite's Menu Entry Swapper plugin.

If you do that it acts like any other item.
