### ISSUE TITLE
Sorting ground items by GE price

### ISSUE THREAD

**Issue by Infinitay** [geheur/More-menu-entry-swaps#34]
> Currently no support for using Grand Exchange value to sort the list, or using item quantities except via ###highlighted### and ###hidden###, which support quantities in the Ground Items plugin. There is also no way to deprioritize menu entries.

I was wondering what the reason for this is? Is it against the rules to do so, or have you not found a way to implement it that you like? I added very basic support for sorting by GE price and it worked fine to my expectations while maintaining the custom list rules too

**Comment by geheur** [comment]
I didn't add it because I didn't need it. There is no rule against it.

**Comment by Infinitay** [comment]
I made a PR for initial support for ground item sorting by price. It's not too extensive as it sorts by comparing the ge/high alch price first, and then it will sort by the user's custom sort list.
