### ISSUE TITLE
Would it be possible to add the bank swaps for bank-like interfaces, e.g. seed vault, price guide, etc?

### ISSUE THREAD

**Issue by swirle13** [geheur/More-menu-entry-swaps#37]
I often find myself attempting to use shift clicking to perform deposit/withdraw/buy/sell all everywhere, but the runelite shift clicking option only works in banks and shops.

My most frequent issue is when I'm trying to shift click deposit/withdraw all my seeds into/from the seed vault in the farming guild. I deposit/withdraw one seed when I expected to deposit/withdraw all. I also run into this when I'm checking prices for the loot I've gotten via the price guide menu, where I also have to right click > add-all.

Would it be possible for this plugin to support those screens as well?

I've otherwise had to update every single shift click option for every seed type, once for each deposit from inventory _and_ withdrawing from the vault, which has been tedious, and I'm sure others have run into this issue too.

This issue has been sitting open on runelite's issues for a couple of years [here](https://github.com/runelite/runelite/issues/10795). I bumped it about a month ago, but they have so many requests that I'm sure it's low priority.

**Comment by geheur** [comment]
https://github.com/runelite/plugin-hub/pull/5764

I can't test the seed vault so hopefully it's correct.

**Comment by geheur** [comment]
I'm assuming it works since no one has complained.

**Comment by swirle13** [comment]
Should "Withdraw-All" occur when holding shift? From the items in the seed vault, there is no change when holding shift, but when depositing from the inventory, it does successfully change to "Deposit-all" when holding shift.

**Comment by geheur** [comment]
It was broken and it will be fixed in 2.5.5 or later.
