### ISSUE TITLE
add support for all max cape options when equipped

### ISSUE THREAD

**Issue by red-eye-jedi** [geheur/More-menu-entry-swaps#38]
add support to enable hotkeys for all options on max cape when equipped, (fishing teleports, other teleports, POH portals, spellbook + features) this would be awesome. please and thanks

**Comment by geheur** [comment]
I don't own a max cape so someone else should make this.

**Comment by red-eye-jedi** [comment]
would still love this, use my max cape basically at 90% or more pieces of content

**Comment by geheur** [comment]
Can you meet me in varrock west bank w420 and trade me the max cape so I can test it out?

**Comment by geheur** [comment]
Hotkey swaps should cover this use case and are avilable in 2.5.0.
