### ISSUE TITLE
Add support for building/removing POH items

### ISSUE THREAD

**Issue by mattclarkdev** [geheur/More-menu-entry-swaps#39]
Restrictions around building/removing POH items can be removed now that Jagex have updated their policies: https://secure.runescape.com/m=news/undead-pirates-tweaks-varlamore-cas--more?oldschool=1

**Comment by StephanBijzitter** [comment]
This has been done already and will be included in the next release :-)
https://github.com/geheur/More-menu-entry-swaps/commit/f80341ffb5431d164fd9d78902eab4138da3c219

**Comment by loscil06** [comment]
Hi! Does submenus for stuff like con capes, fishing capes, hunter capes will also be suported?

**Comment by geheur** [comment]
@loscil06 No. Jagex said it's only for specific items. Not jewellery. Not other capes.

The original issue topic is released in 2.5.2 or later.
