### ISSUE TITLE
menu entry swapping not working correctly with seed vault since last update

### ISSUE THREAD

**Issue by trihard7237** [geheur/More-menu-entry-swaps#4]
shift banking works as intended in the bank, but in the seed vault when withdraw x has a hotkey it brings up the set-x menu instead, and when enabling bank all it does not work at all.

**Comment by geheur** [comment]
hmm I was not aware that this ever even worked with the seed vault.

**Comment by geheur** [comment]
Pretty sure this was never possible in the first place.
