### ISSUE TITLE
Double (Or Increase) the number of Hotkey Swaps Available

### ISSUE THREAD

**Issue by StephenWolters** [geheur/More-menu-entry-swaps#40]
With the new availability to swap the achievement diary cape teleports the default 10 hotkey swaps doesn't let you use all the diary cape teles with a hotkey (it has 1-9 and A-G for a total of 16 options). 
It seems like 20 would be a nice number of hotkey swaps to handle all Diary cape and Max Cape Teles as well as a few extra for whatever.
If it was possible to add an unlimited number of hotkeys with an add button that would be even better, but I assume just going from 10-20 would be easier.

**Comment by geheur** [comment]
Haha, I did count the total number of swaps and figured someone would ask for it. Didn't expect it to happen in less than 24 hours though.

I'd probably just up it to 20. Few people need that many and arbitrary numbers of hotkeys would mean I'd have to split the UI between the config panel and a custom side panel, or something like that. Awkward, and more work.

**Comment by geheur** [comment]
added in 2.5.4
