### ISSUE TITLE
Suggestion for your custom swaps page

### ISSUE THREAD

**Issue by clscndd** [geheur/More-menu-entry-swaps#43]
I don't know how to suggest an edit to your custom swaps, but _last-destination*, fairy ring*_   can prioritize the last destination on fairy rings (instead of Zanaris or Configure options), maybe this is helpful as an example for the page :) 

Thanks for the plugin, it's very helpful!

**Comment by geheur** [comment]
There is actually a non-custom swap for fairy rings, if you scroll down. So I don't think adding this is necessary.

Glad you found the plugin helpful :).
