### ISSUE TITLE
Need some Help

### ISSUE THREAD

**Issue by AardPlugs** [geheur/More-menu-entry-swaps#44]
Not sure if am the one doing something wrong here, or it just doesnt work. but i cant get it to prioritize Noted Items over others Eg
Am i using the noted: part wrong ?

Take,noted:Adamantite bar*,Take,*

**Comment by geheur** [comment]
you cannot use `noted:` in the custom swaps section, only in the ground item reorder section. e.g.

```
unnoted:adamantite bar,-1
```

**Comment by AardPlugs** [comment]
Could you in Future Update maybe Add Support for Item Ids, or some work around, to use Notes in Swap Section ?

**Comment by geheur** [comment]
what situation do you need this for?

**Comment by AardPlugs** [comment]
Well i just made my Own Prioritizing list,  Eg Click Objects,Looting,Attacking Npc,  like in some cases i rather loot certain items over Attack Npc, but i would like to expand the List with some (Noted) items, lets say i want Adamant Bars over Attacking Npcs, i only want Noted Bars, not Unnoted.  Eg
