### ISSUE TITLE
Setting All bank option to CTRL is messing with chat.

### ISSUE THREAD

**Issue by DylanM05** [geheur/More-menu-entry-swaps#45]
When I enable Custom Menu Swap -> Bank -> All and set it to CTRL, it makes it so when I CTRL click on a players chat message, the first option is Report.  making it so when I ctrl click to walk in PVM and accidentily click a message, I dont move and it brings up the report screen.
![image](https://github.com/geheur/More-menu-entry-swaps/assets/97370609/dec4dd10-df84-4dfc-8c36-61846cccdc6e)
![image](https://github.com/geheur/More-menu-entry-swaps/assets/97370609/23274bdc-3ec8-48d1-93a5-d888e0636208)

**Comment by geheur** [comment]
yes, it looks like I made a mistake in the last update. I'll fix it.

**Comment by geheur** [comment]
Should be fixed now!
