### ISSUE TITLE
Holding Shift with different menu swappers enabled or disabled wants to destroy TOA Supplies pouch instead if shift resupply

### ISSUE THREAD

**Issue by Akeno121** [geheur/More-menu-entry-swaps#48]
When enabling this plugin it wants to destroy the supplies pouch in TOA i got shift set to resupply and left click to opem but for some reason it doesnt wanna do resupply and only destroy the pouch.
![image](https://github.com/user-attachments/assets/5840b08f-f283-410a-bd7c-942b1b55362b)
![image](https://github.com/user-attachments/assets/52484ea4-f256-4ebe-a4f6-d67aa5ee9482)

**Comment by geheur** [comment]
did you set anything in `Custom Swaps (hotkeys)`?
I can't think of a reason why my plugin would modify those options unless you set something in it.

**Comment by Akeno121** [comment]
Heey no they empty but i did setup swap use hotkey and eat wield hotkeys but the actual hotkey part is empty and only seems to go worn when i enablr the plugin

**Comment by Akeno121** [comment]
![image](https://github.com/user-attachments/assets/e36efe47-aaa4-42c9-b4ed-32890b8d523e)
![image](https://github.com/user-attachments/assets/8fffe90b-efde-4f78-bdcf-7520cde41ce8)
![image](https://github.com/user-attachments/assets/78287881-5895-40ae-b064-1f7c33d0f817)
![image](https://github.com/user-attachments/assets/b620ea61-ed60-45f4-9d2b-bdd87ef22141)
![image](https://github.com/user-attachments/assets/e1506ee7-0dfe-49b2-adf7-fda086a70734)

**Comment by geheur** [comment]
Should be fixed in 2.5.8.
