### ISSUE TITLE
Needs Update Pretty Please!

### ISSUE THREAD

**Issue by Hash4Kash** [geheur/More-menu-entry-swaps#53]
I use this awesome plugin everyday, its a must have for me. If you could fix it ASAP, that would be much appreciated. Thank you very much!

**Comment by achen88** [comment]
same here -- @geheur let me know what needs to be done and I'd be happy to contribute, not sure what caused the incompatibility

**Comment by geheur** [comment]
The fix should be out. Thanks for the offer of help though :).
