### ISSUE TITLE
Don't swap deprioritized "Take" doesn't work.

### ISSUE THREAD

**Issue by notheowner** [geheur/More-menu-entry-swaps#55]
Under Ground Item Sort -> Don't swap deprioritized "Take" doesn't seem to work. In my case I have `Take, *` in the swaps so picking up loot is always on top of mobs and stuff under low value would be ignored with this toggle.

Since yesterday's game update, doesn't seem like it respects the hidden items from Ground Items anymore.

Example Image 
![image](https://github.com/user-attachments/assets/abab63d0-2b8e-4f58-952a-dc333453f613)
Dust is hidden and "Deprioritize Menu Hidden Items" is ticked on Ground Items
` Don't swap deprioritized "Take"` is enabled.

**Comment by geheur** [comment]
I think this will be fixed in 2.5.9
