### ISSUE TITLE
Conflicts with default MES on 2.5.9

### ISSUE THREAD

**Issue by inewman** [geheur/More-menu-entry-swaps#57]
I use Menu Entry Swapper (the default RuneLite plugin) to swap Max Cape shift click to Teleports. This works by itself.

With Custom Menu Swaps 2.5.9 enabled, the option becomes Warriors' Guild. I do not use any swaps for the Max Cape via Custom Menu Swaps. With the plugin disabled, MES works as intended again.

Of note, Warriors' Guild is the first option in the Teleports submenu.

**Comment by Daxxed** [comment]
Same thing happened to Achievement Diary Cape
I had left click on Jarr and shift click on teleport, but shift click defaults to #1/two pints now instead.

**Comment by geheur** [comment]
do either of y'all have "don't swap deprioritized take" on under ground item order, and does disabling it fix the issue?

**Comment by inewman** [comment]
I do not have that option enabled.

**Comment by vikke1234** [comment]
I can't replicate this, works fine for me.

**Comment by Daxxed** [comment]
> I can't replicate this, works fine for me.
A fix was pushed yesterday and merged a few hours before you posted this. But yes, works fine now and issue can be closed.

**Comment by Daxxed** [comment]
> > I can't replicate this, works fine for me.
> >
A fix was pushed last night and merged a few hours before you posted this. But yes, works fine now and issue can be closed.
