### ISSUE TITLE
[Feature Request] swappable advertisement board

### ISSUE THREAD

**Issue by iligalodin** [geheur/More-menu-entry-swaps#6]
hey, thanks for this amazing plugin!

usually when i play the game i use other peoples houses because of my low const, and therefore have set my default interaction with the advertisement boards to "visit last".

this is where my suggestion comes in, on log-on your visit last is set to nothing, gives an error message like "you havent visited bla bla bla" so i was wondering if we could get it where holding down a hotkey switches the interaction to "view advertisements" (or whatever it actually is)?

the problem is a mild inconvenience but  with this plugin it could become a QOL

**Comment by geheur** [comment]
This sounds like it would be possible now.
