### ISSUE TITLE
Doesn't work with any attempted configuration

### ISSUE THREAD

**Issue by Luunae** [geheur/More-menu-entry-swaps#62]
I've tried:

- Varying levels of formatting swap entries, down to the simplest of only one thing. (e.g. Custom swaps "Use" then mousing over a potion)
- Disabling all other plugins to see if it was a conflict issue.
- Try a variety of items, and the handful of common entries. (Individually: Use, Drop, Examine)

**Comment by geheur** [comment]
Did you read the instructions sections?

**Comment by Luunae** [comment]
Uuuuugh, that was really dumb of me. I'm sorry for wasting your time with this and doing a wrong bug report.
